# Generated by Django 4.2.2 on 2023-06-15 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_product_prodapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.FloatField(blank=True, default='', null=True),
        ),
    ]
