# Generated by Django 4.2.2 on 2023-06-25 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_myotp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Myotp',
        ),
    ]
