# Generated by Django 4.2.2 on 2023-06-29 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_tokenregister'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
